### ISSUE TITLE
rebuild-cljs

### ISSUE THREAD

**Issue by funkotron** [weavejester/duct-figwheel-component#2]
I'm sure I'm overlooking something here, and if so please forgive me.

I'd like to run a build on all files to start with, the equivalent of `lein cljsbuild once`, and am trying to do so using your `rebuild-cljs` function which sounds like it does this:

```
"Tell a Figwheel server component to rebuild all ClojureScript source files,
and to send the new code to the connected clients."
```

However I get a Null Pointer exception when it executes `(reset! state (mapv (partial start-build builder) builds))` I believe because builds is nil. Is there a correct way of doing this?

Thank you.

**Comment by weavejester** [comment]
Are you running it with the component stopped?
